site_name: Mapa da Cultura

extra_css:
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt

nav:
    - Home: index.md
    - Planejamento: planejamento.md
    - Análise de requisitos:
        - Análise de tarefas: analise_de_tarefas.md
    - Atas:
          - 12/08/2021: atas/reuniao-12-08-2021.md
    - Apresentações: apresentacoes.md

