site_name: Mapa da Cultura

extra_css:
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt

nav:
    - Home: index.md
    - Planejamento: planejamento.md
    - Análise de Requisitos:
          - Personas: analise-de-requisitos/personas.md
          - Análise de tarefas:

    - Atas:
          - 12/08/2021: atas/reuniao-12-08-2021.md
          - 19/08/2021: atas/reuniao-19-08-2021.md
    - Apresentações: apresentacoes.md
