site_name: My docs

extra_css:
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt

nav:
    - Home: index.md
    - Planejamento: planejamento.md
    - Atas:
          - 12/08/2021: atas/reuniao-12-08-2021.md
