site_name: Tribunal de Justiça do Estado do Amapá

extra_css:
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    logo: assets/logo.png

nav:
    - Home: index.md
    - Planejamento: planejamento.md
    - Análise de Requisitos:
          - Personas: analise-de-requisitos/personas.md
          - Análise de tarefas: analise-de-requisitos/analise_de_tarefas.md
          - Metas de usabilidade: analise-de-requisitos/metas-de-usabilidade.md

    - Atas:
          - 12/08/2021: atas/reuniao-12-08-2021.md
          - 19/08/2021: atas/reuniao-19-08-2021.md
    - Apresentações: apresentacoes.md
