site_name: Tribunal de Justiça do Estado do Amapá

extra_css:
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    logo: assets/logo.png
    favicon: assets/logo.png

nav:
    - Home: index.md
    - Planejamento: planejamento.md
    - Análise de Requisitos:
          - Perfil do Usuário: base/analise_de_tarefas/perfil_do_usuario.md
          - Personas: analise-de-requisitos/personas.md
          - Análise de Tarefas: analise-de-requisitos/analise_de_tarefas.md
          - Guia de Estilo: analise-de-requisitos/guia-de-estilo.md
          - Metas de usabilidade: analise-de-requisitos/metas-de-usabilidade.md
          - Princípios Gerais de Projeto: analise-de-requisitos/principios_gerais.md
    - Design, avaliação e desenvolvimento:
          - Nível 1:
                - Storyboards:
                      - Planejamento da avaliação do storyboard: design-ava-des/nivel-1/storyboards/plan-ava-storyboard.md
                      - Storyboards: design-ava-des/nivel-1/storyboards/storyboards.md
                      - Relato dos resultados da avaliação do storyboard: design-ava-des/nivel-1/storyboards/res-ava-storyboard.md
          - Nível 2:
          - Nível 3:

    - Atas:
          - 12/08/2021: atas/reuniao-12-08-2021.md
          - 19/08/2021: atas/reuniao-19-08-2021.md
          - 27/08/2021: atas/reuniao-27-08-2021.md
    - Apresentações: apresentacoes.md
