site_name: Tribunal de Justiça do Estado do Amapá

extra_css:
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt
    logo: assets/logo.png
    favicon: assets/logo.png

nav:
      - Home: index.md
      - Planejamento: planejamento.md
      - Análise de Requisitos:
            - Perfil do Usuário: base/analise_de_tarefas/perfil_do_usuario.md
            - Personas: analise-de-requisitos/personas.md
            - Análise de Tarefas: analise-de-requisitos/analise_de_tarefas.md
            - Guia de Estilo: analise-de-requisitos/guia-de-estilo.md
            - Metas de Usabilidade: analise-de-requisitos/metas-de-usabilidade.md
            - Princípios Gerais de Projeto: analise-de-requisitos/principios_gerais.md
      - Design, Avaliação e Desenvolvimento:
            - Nível 1:
                  - Storyboards:
                        - Storyboards: design-ava-des/nivel-1/storyboards/storyboards.md
                        - Planejamento da Avaliação do Storyboard: design-ava-des/nivel-1/storyboards/plan-ava-storyboard.md
                        - Relato dos Resultados da Avaliação do Storyboard: design-ava-des/nivel-1/storyboards/res-ava-storyboard
                  - Análise de Tarefas:
                        - Planejamento da Avaliação da Análise de Tarefas: design-ava-des/nivel-1/analise-tarefas/planejamento_avaliacao.md
                        - Resultados da Avaliação da Análise de Tarefas: 
                              - Tarefa 1: design-ava-des/nivel-1/analise-tarefas/tarefa1.md
                              - Tarefa 2: design-ava-des/nivel-1/analise-tarefas/tarefa2.md
                              - Tarefa 3: design-ava-des/nivel-1/analise-tarefas/tarefa3.md
            - Nível 2:
                        - Protótipo de Papel: design-ava-des/nivel-2/prototipo-de-papel.md
                        - Planejamento da Avaliação do Protótipo de Baixa Fidelidade: design-ava-des/nivel-2/planejamento_avaliacao.md
                        - Resultados da Avaliação do Protótipo de Baixa Fidelidade: design-ava-des/nivel-2/resultado_avaliacao.md
            - Nível 3:
                        - Protótipo de Alta: design-ava-des/nivel-3/prototipo-de-alta.md
                        - Planejamento da Avaliação do Protótipo de Alta Fidelidade: design-ava-des/nivel-3/planejamento_avaliacao_prot_alta.md
                        - Relato dos Resultados da Avaliação do Protótipo de Alta Fidelidade: design-ava-des/nivel-3/resultado-avaliacao.md
      - Análise:
            - Verificação:
                  - Planejamento da Verificação: analise/verificacao/planejamento.md
                  - Perfil do Usuário: analise/verificacao/perfil-do-usuario.md
                  - Personas: analise/verificacao/personas.md
                  - Análise de Tarefas: analise/verificacao/analise-de-tarefas.md
                  - Metas de Usabilidade: analise/verificacao/metas-de-usabilidade.md
                  - Princípios Gerais do prjeto: analise/verificacao/ver_principios_gerais.md
                  - Guia de Estilo: analise/verificacao/guia-de-estilo.md
                  - Planejamento da Avaliação da Análise de Tarefas: analise/verificacao/plan-ava-analise-de-tarefas.md
                  - Planejamento da Avaliação do Storyboard: analise/verificacao/ver_planej_ava_storyboard.md                    
                  - Storyboards: analise/verificacao/storyboards.md
                  - Relato dos Resultados da Avaliação do Storyboard: analise/verificacao/ver_result_ava_storyboard.md
                  - Protótipo de Baixa Fidelidade: analise/verificacao/prot-baixa.md
                  - Planejamento da Avaliação do Protótipo de Baixa Fidelidade: analise/verificacao/plan-prot-baixa.md
                  - Relato dos Resultados da Avaliação do Protótipo de Baixa Fidelidade: analise/verificacao/resu-prot-baixa.md
                  - Planejamento da Avaliação do Protótipo de Alta Fidelidade: analise/verificacao/plan-prot-alta.md
                  - Protótipo de Alta Fidelidade: analise/verificacao/prot-alta.md
                  - Relato dos Resultados da Avaliação do Protótipo de Alta Fidelidade: analise/verificacao/ver_result_ava_prototipo_alta.md          
      - Atas:
            - Entrega 1 - 12/08/2021: atas/reuniao-12-08-2021.md
            - Entrega 2 - 19/08/2021: atas/reuniao-19-08-2021.md
            - Entrega 3 - 27/08/2021: atas/reuniao-27-08-2021.md
            - Entrega 4 - 03/09/2021: atas/reuniao-03-09-2021.md
            - Entrega 5 - 12/09/2021: atas/reuniao-12-09-2021.md
            - Entrega 6 - 19/09/2021: atas/reuniao-19-09-2021.md
            - Entrega 7 - 01/10/2021: atas/reuniao-01-10-2021.md
      - Apresentações: apresentacoes.md
