site_name: Mapa da Cultura

extra_css:
    - assets/stylesheets/extra.css

theme:
    name: material
    language: pt

nav:
    - Home: index.md
    - Planejamento: planejamento.md
    - Análise de Requisitos:
          - Perfil do Usuário: base/analise_de_tarefas/perfil_do_usuario.md
    - Atas:
          - 12/08/2021: atas/reuniao-12-08-2021.md
          - 19/08/2021: atas/reuniao-19-08-2021.md
          - 27/08/2021: atas/reuniao-27-08-2021.md
    - Apresentações: apresentacoes.md
